name: ppo_balancer
channels:
    - https://conda.anaconda.org/conda-forge
dependencies:
    - gin-config >=0.5.0
    - gymnasium >=0.28.1
    - stable-baselines3 >=2.1.0
    - tensorboard
    - upkie >=5.1.0
