# -*- python -*-
#
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

py_library(
    name = "wrappers",
    srcs = [
        "__init__.py",
        "wheeled_inverted_pendulum_reward.py",
    ],
    deps = [
        "@upkie//upkie/envs/wrappers",
    ],
)
