name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    lint:
        name: "Lint code"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Setup Python environment"
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: "Install dependencies"
              run: |
                  python -m pip install ruff

            - name: "Check Python code formatting"
              run: |
                  ruff check ppo_balancer

    ci_success:
        name: "CI success"
        runs-on: ubuntu-latest
        needs: [lint]
        steps:
            - run: echo "CI workflow completed successfully"
